name: em-template
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - plotly
  - pyvista
  - nglview
  - h5py
  - imageio
  - av # instead of imageio-ffmpeg
  - ipywidgets
  - ipympl
  - jupyterlab
  - jupyterlab-myst
  - trame
  - trame-vtk
  - trame-vuetify
  - 'nodejs>=20,<21'
  - mystmd
